from django.db import models
from accounts.models import coiffeur_profil
from django.db.models.signals import post_save

class images(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)

class kuafor_hizmet(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    service = models.CharField(max_length=128)
    price = models.CharField(max_length=128)

def create_gunler(instance, created, **kwargs):
    if created:
        kuafor_gun1.objects.create(coiffeur=instance)
        kuafor_gun2.objects.create(coiffeur=instance)
        kuafor_gun3.objects.create(coiffeur=instance)
        kuafor_gun4.objects.create(coiffeur=instance)
        kuafor_gun5.objects.create(coiffeur=instance)
        kuafor_gun6.objects.create(coiffeur=instance)
        kuafor_gun7.objects.create(coiffeur=instance)
post_save.connect(receiver=create_gunler, sender=coiffeur_profil)

class kuafor_gun1(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")


class kuafor_gun2(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")


class kuafor_gun3(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")


class kuafor_gun4(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")



class kuafor_gun5(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")


class kuafor_gun6(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")



class kuafor_gun7(models.Model):
    coiffeur = models.ForeignKey(coiffeur_profil, on_delete=models.CASCADE)
    sekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    sekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    dokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    on = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    oniki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onucB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondort = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondortB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbes = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onbesB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onalti = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onaltiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyedi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onyediB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekiz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    onsekizB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuz = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    ondokuzB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmi = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibir = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmibirB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiiki = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiikiB = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")
    yirmiuc = models.CharField(max_length=128, default="btn btn-default btn-lg btn-success")