# Generated by Django 2.2.2 on 2019-07-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190701_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='randevu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=128)),
                ('person', models.CharField(blank=True, max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('hour', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('coiffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coiffeur_profil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
