# Generated by Django 2.2.2 on 2019-07-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coiffeur_person'),
        ),
    ]
