# Generated by Django 2.2.2 on 2019-07-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0008_randevu_stateday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randevu',
            old_name='stateday',
            new_name='daystate',
        ),
    ]
