# Generated by Django 2.2.2 on 2019-07-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0009_auto_20190729_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='daystate',
        ),
    ]
