# Generated by Django 2.2.2 on 2019-07-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0012_auto_20190729_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coiffeur_person'),
        ),
    ]
