# Generated by Django 2.2.2 on 2019-07-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190701_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coiffeur_person',
            name='coiffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coiffeur_profil'),
        ),
    ]
