# Generated by Django 2.2.2 on 2019-07-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coiffeur_profil_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coiffeur_profil',
            name='slug',
        ),
    ]
