# Generated by Django 2.2.2 on 2019-07-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
