# Generated by Django 2.2.2 on 2019-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('passwordRepeat', models.CharField(max_length=128)),
                ('favorite', models.IntegerField()),
            ],
        ),
    ]
