# Generated by Django 2.2.2 on 2019-06-26 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('passwordRepeat', models.CharField(max_length=128)),
                ('favorite', models.IntegerField()),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
