# Generated by Django 2.2.2 on 2019-06-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190626_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='barbers',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='text',
        ),
    ]
