# Generated by Django 2.2.2 on 2019-06-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190626_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
