# Generated by Django 2.2.2 on 2019-06-29 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='asada',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
