# Generated by Django 2.2.2 on 2019-06-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_location_asada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='asada',
        ),
    ]
