# Generated by Django 2.2.2 on 2019-07-18 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190701_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
