# Generated by Django 2.2.2 on 2019-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(editable=False, max_length=128, unique=True),
        ),
    ]
