# Generated by Django 2.2.2 on 2019-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaforler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuafor_gun1',
            name='data',
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='dokuz',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='dokuzB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='on',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onalitB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onalti',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onbes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onbesB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onbir',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onbirB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='ondokuz',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='ondokuzB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='ondort',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='ondortB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='oniki',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onikiB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onsekiz',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onsekizB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onuc',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onucB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onyedi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='onyediB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='sekiz',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='sekizB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmiB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmibir',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmibirB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmiiki',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmiikiB',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kuafor_gun1',
            name='yirmiuc',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
