# Generated by Django 2.2.2 on 2019-07-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaforler', '0002_auto_20190709_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuafor_gun1',
            name='sekiz',
            field=models.CharField(default='btn btn-default btn-lg btn-success', max_length=128),
        ),
        migrations.AlterField(
            model_name='kuafor_gun1',
            name='sekizB',
            field=models.CharField(default='btn btn-default btn-lg btn-success', max_length=128),
        ),
    ]
