# Generated by Django 2.2.2 on 2019-07-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaforler', '0003_auto_20190710_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuafor_gun1',
            name='sekiz',
            field=models.CharField(default='btn btn-default btn-lg btn-success2', max_length=128),
        ),
    ]
