# Generated by Django 2.2.2 on 2019-07-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaforler', '0006_auto_20190710_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuafor_gun1',
            name='sekiz',
            field=models.BooleanField(default=False),
        ),
    ]
