# Generated by Django 2.2.2 on 2019-07-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190704_1501'),
        ('kuaforler', '0013_kuafor_gun3_kuafor_gun4_kuafor_gun5_kuafor_gun6_kuafor_gun7'),
    ]

    operations = [
        migrations.CreateModel(
            name='kuafor_hizmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('coiffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coiffeur_profil')),
            ],
        ),
    ]
